{% set version = "0.5.0" %}

package:
  name: mpld3
  version: {{ version }}

source:
  fn: mpld3-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mpld3/mpld3-{{ version }}.tar.gz
  sha256: dccc708cc3c997c4478ab9fe4e973a75950683761e99b9e2b89cc96548ac0a57

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - jinja2
    - matplotlib-base

test:
  imports:
    - mpld3

about:
  home: http://mpld3.github.com
  license: BSD-3-Clause
  license_file: LICENSE
  summary: D3 Viewer for Matplotlib

extra:
  recipe-maintainers:
    - etgalloway
    - jakevdp
    - ocefpaf
