{% set version = "0.3" %}

package:
  name: mpld3
  version: {{ version }}

source:
  fn: mpld3-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mpld3/mpld3-{{ version }}.tar.gz
  sha256: 4d455884a211bf99b37ecc760759435c7bb6a5955de47d8daf4967e301878ab7

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jinja2
    - matplotlib

test:
  imports:
    - mpld3

about:
  home: http://mpld3.github.com
  license: BSD 3-Clause
  summary: 'D3 Viewer for Matplotlib.'

extra:
  recipe-maintainers:
    - etgalloway
    - jakevdp
    - ocefpaf
