{% set version = "0.5.7" %}

package:
  name: mpld3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mpld3/mpld3-{{ version }}.tar.gz
  sha256: c589db8b661aee25c93e198e2e18ed47b9a96951de41d96241345acec5f819ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jinja2
    - matplotlib-base

test:
  imports:
    - mpld3
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://mpld3.github.com
  license: BSD-3-Clause
  license_file: LICENSE
  summary: D3 Viewer for Matplotlib

extra:
  recipe-maintainers:
    - etgalloway
    - jakevdp
    - ocefpaf
