{% set version = "0.5.5" %}

package:
  name: mpld3
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mpld3/mpld3-{{ version }}.tar.gz
  sha256: b080f3535238a71024c0158280ab4f6091717c45347c41c907012f8dd6da1bd5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jinja2
    - matplotlib-base

test:
  imports:
    - mpld3
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://mpld3.github.com
  license: BSD-3-Clause
  license_file: LICENSE
  summary: D3 Viewer for Matplotlib

extra:
  recipe-maintainers:
    - etgalloway
    - jakevdp
    - ocefpaf
