{% set version = "0.5.11" %}

package:
  name: mpld3
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mpld3/mpld3-{{ version }}.tar.gz
  sha256: bffe2c93f8b406f8d4dc059565dfecb4779e8a1fc50bfbb4e7f5d476a274eab7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - jinja2
    - matplotlib-base

test:
  imports:
    - mpld3
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://mpld3.github.com
  license: BSD-3-Clause
  license_file: LICENSE
  summary: D3 Viewer for Matplotlib

extra:
  recipe-maintainers:
    - etgalloway
    - jakevdp
    - ocefpaf
