{% set version = "0.5.1" %}

package:
  name: mpld3
  version: {{ version }}

source:
  fn: mpld3-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/m/mpld3/mpld3-{{ version }}.tar.gz
  sha256: 1677a314125ff2984e2f291d595188d5ee8ca66ac21b0c2c8633961bc33a7bf8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jinja2
    - matplotlib-base

test:
  imports:
    - mpld3
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://mpld3.github.com
  license: BSD-3-Clause
  license_file: LICENSE
  summary: D3 Viewer for Matplotlib

extra:
  recipe-maintainers:
    - etgalloway
    - jakevdp
    - ocefpaf
