travis:
  secure:
    BINSTAR_TOKEN: L2ftIvM9iZcSWpZ4hghML7t5ZAlrHCc6wSw1f3bhn2vSMQJuk5qWt+4zYzm3+1C1oBr5rdXEfQsdZX6vC+4eeCh9tSychqVIuyXXkSjX9CYMKuarg0Pbq2VLRzdDvY5TVMtLL9/QuXJR33lwheDsjKWV/iWgeTvRb3UQTGY5hRFsOitUDR3/eJkIL2Kn/4oGwWeI3gBMqv27j3/NuZGCbKWxTwU/cbI3LiDwBMy7EOjNy3T/YdjsCUK4Bk/63Juf/Uji+MfvzzIluqlgTj4dlzDbVHvAGWsSuEFEGjiVDj7sgheRT58RHVpIaZFT9HZrCXOJIqbQlajuOMocMd5WoIP3JHeuzpRWf59QrzUlo86U2UmSzBnMhKZVNnhff0fEVFLGNJ8SDRooxZAio6oRZduZKsTDjm2XuLXdkqa6D5C7eMPvt8NfmawqLYw8raU5KUYe14m8Apz49mmmdXlsp0+KTuFusuHQYrQI6Ucx3p10XeTdwsWpmn2krLPjUVKY8Q9NK4WHsIp8Hq47LCtIAo1vn6BfuVoapmm2fqqnUrtHBs1n5n9Nq06bcC77wUWuRo3Rg6boezu2CSVfWKJ5ZipHCufVds03vv6XREN31yqu7ZZbi11epY22Ay4BeFwxtthA4H72QI35B6IqJubdicc8PUJz3Nynik0Dpm8NPdI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
